version: '3.1'
services:
#ZONA COM
     
  host2: 
    build:
      dockerfile: images/webserver.dockerfile
      context: .
    ports: 
      - 8080:80
    volumes: 
      - ./app:/app
    environment: 
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80